name: bt_tuan7
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl: ^0.19.0
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  http: ^1.2.1
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/files/'
